/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PreOrderRouteImport } from './routes/pre-order'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MealLogRouteImport } from './routes/meal-log'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as ProviderQrRouteImport } from './routes/provider.qr'
import { Route as ProviderOrdersRouteImport } from './routes/provider.orders'
import { Route as ProviderMenuRouteImport } from './routes/provider.menu'
import { Route as ProviderAnalyticsRouteImport } from './routes/provider.analytics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PreOrderRoute = PreOrderRouteImport.update({
  id: '/pre-order',
  path: '/pre-order',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MealLogRoute = MealLogRouteImport.update({
  id: '/meal-log',
  path: '/meal-log',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderQrRoute = ProviderQrRouteImport.update({
  id: '/provider/qr',
  path: '/provider/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderOrdersRoute = ProviderOrdersRouteImport.update({
  id: '/provider/orders',
  path: '/provider/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderMenuRoute = ProviderMenuRouteImport.update({
  id: '/provider/menu',
  path: '/provider/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAnalyticsRoute = ProviderAnalyticsRouteImport.update({
  id: '/provider/analytics',
  path: '/provider/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collect': typeof CollectRoute
  '/mcp': typeof McpRoute
  '/meal-log': typeof MealLogRoute
  '/menu': typeof MenuRoute
  '/pre-order': typeof PreOrderRoute
  '/scan': typeof ScanRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/provider/analytics': typeof ProviderAnalyticsRoute
  '/provider/menu': typeof ProviderMenuRoute
  '/provider/orders': typeof ProviderOrdersRoute
  '/provider/qr': typeof ProviderQrRoute
  '/provider/': typeof ProviderIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collect': typeof CollectRoute
  '/mcp': typeof McpRoute
  '/meal-log': typeof MealLogRoute
  '/menu': typeof MenuRoute
  '/pre-order': typeof PreOrderRoute
  '/scan': typeof ScanRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/provider/analytics': typeof ProviderAnalyticsRoute
  '/provider/menu': typeof ProviderMenuRoute
  '/provider/orders': typeof ProviderOrdersRoute
  '/provider/qr': typeof ProviderQrRoute
  '/provider': typeof ProviderIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collect': typeof CollectRoute
  '/mcp': typeof McpRoute
  '/meal-log': typeof MealLogRoute
  '/menu': typeof MenuRoute
  '/pre-order': typeof PreOrderRoute
  '/scan': typeof ScanRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/provider/analytics': typeof ProviderAnalyticsRoute
  '/provider/menu': typeof ProviderMenuRoute
  '/provider/orders': typeof ProviderOrdersRoute
  '/provider/qr': typeof ProviderQrRoute
  '/provider/': typeof ProviderIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/collect'
    | '/mcp'
    | '/meal-log'
    | '/menu'
    | '/pre-order'
    | '/scan'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/provider/analytics'
    | '/provider/menu'
    | '/provider/orders'
    | '/provider/qr'
    | '/provider/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/collect'
    | '/mcp'
    | '/meal-log'
    | '/menu'
    | '/pre-order'
    | '/scan'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/provider/analytics'
    | '/provider/menu'
    | '/provider/orders'
    | '/provider/qr'
    | '/provider'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/collect'
    | '/mcp'
    | '/meal-log'
    | '/menu'
    | '/pre-order'
    | '/scan'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/provider/analytics'
    | '/provider/menu'
    | '/provider/orders'
    | '/provider/qr'
    | '/provider/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CollectRoute: typeof CollectRoute
  McpRoute: typeof McpRoute
  MealLogRoute: typeof MealLogRoute
  MenuRoute: typeof MenuRoute
  PreOrderRoute: typeof PreOrderRoute
  ScanRoute: typeof ScanRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProviderAnalyticsRoute: typeof ProviderAnalyticsRoute
  ProviderMenuRoute: typeof ProviderMenuRoute
  ProviderOrdersRoute: typeof ProviderOrdersRoute
  ProviderQrRoute: typeof ProviderQrRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-order': {
      id: '/pre-order'
      path: '/pre-order'
      fullPath: '/pre-order'
      preLoaderRoute: typeof PreOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-log': {
      id: '/meal-log'
      path: '/meal-log'
      fullPath: '/meal-log'
      preLoaderRoute: typeof MealLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/provider'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/qr': {
      id: '/provider/qr'
      path: '/provider/qr'
      fullPath: '/provider/qr'
      preLoaderRoute: typeof ProviderQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/orders': {
      id: '/provider/orders'
      path: '/provider/orders'
      fullPath: '/provider/orders'
      preLoaderRoute: typeof ProviderOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/menu': {
      id: '/provider/menu'
      path: '/provider/menu'
      fullPath: '/provider/menu'
      preLoaderRoute: typeof ProviderMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/analytics': {
      id: '/provider/analytics'
      path: '/provider/analytics'
      fullPath: '/provider/analytics'
      preLoaderRoute: typeof ProviderAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CollectRoute: CollectRoute,
  McpRoute: McpRoute,
  MealLogRoute: MealLogRoute,
  MenuRoute: MenuRoute,
  PreOrderRoute: PreOrderRoute,
  ScanRoute: ScanRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProviderAnalyticsRoute: ProviderAnalyticsRoute,
  ProviderMenuRoute: ProviderMenuRoute,
  ProviderOrdersRoute: ProviderOrdersRoute,
  ProviderQrRoute: ProviderQrRoute,
  ProviderIndexRoute: ProviderIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
